[tools]
node                            = "latest"
rust                            = "latest"
fzf                             = "latest"
ripgrep                         = "latest"
fd                              = "latest"
ag                              = "latest"
tmux                            = "latest"
pandoc                          = "latest"
ruff                            = "latest"
uv                              = "latest"
lua-language-server             = "latest"
opencode                        = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@google/gemini-cli"        = "latest"
"npm:@github/copilot"           = "latest"
