font_family      DejaVu Sans Mono Book
bold_font        DejaVu Sans Mono Bold
italic_font      DejaVu Sans Mono Oblique
bold_italic_font DejaVu Sans Mono Bold Oblique
font_size 12
symbol_map U+23FB-U+23FE,U+2665,U+26A1,U+2B58,U+E000-U+E00A,U+E0A0-U+E0A3,U+E0B0-U+E0D4,U+E200-U+E2A9,U+E300-U+E3E3,U+E5FA-U+E6AA,U+E700-U+E7C5,U+EA60-U+EBEB,U+F000-U+F2E0,U+F300-U+F32F,U+F400-U+F4A9,U+F500-U+F8FF,U+F0001-U+F1AF0 Symbols Nerd Font Mono

cursor_trail 4
cursor_trail_decay 0.05 0.2
cursor_trail_start_threshold 8

copy_on_select yes
clipboard_control write-clipboard write-primary no-append
sync_to_monitor yes
enable_audio_bell no
remember_window_size  no
initial_window_width  800
initial_window_height 600
enabled_layouts tall:bias=60

tab_bar_style slant

wayland_titlebar_color system
macos_titlebar_color system
macos_option_as_alt left

map shift+enter send_text all \x1b[13;2u
map ctrl+enter send_text all \x1b[13;5u
map shift+space send_text all \x1b[32;2u
map ctrl+space send_text all \x1b[32;5u
map ctrl+tab send_text all \x1b[9;5u

map ctrl+shift+r new_tab_with_cwd
map ctrl+shift+a>m no_op
map ctrl+shift+a>l no_op
map ctrl+shift+a>1 no_op
map ctrl+shift+a>d no_op

# See https://sw.kovidgoyal.net/kitty/conf/#sample-kitty-conf for customization
include local.conf
include color.conf
