[tools]
node = "latest"
rust = "latest"
fzf = "latest"
ripgrep = "latest"
fd = "latest"
ag = "latest"
tmux = "latest"
pandoc = "latest"
ruff = "latest"
uv = "latest"
lua-language-server = "latest"
bun = "latest"
