# Keybindings
keybinding:
  universal:
    prevPage: <c-u>
    nextPage: <c-d>
    scrollUpMain-alt2: <c-b>
    scrollDownMain-alt2: <c-f>
    undo: u
    redo: <C-r>
    copyToClipboard: y
    openRecentRepos: <c-o>
    extrasMenu: ','
  status:
    checkForUpdate: U
    recentRepos: <c-o>
  files:
    openStatusFilter: F
    copyFileInfoToClipboard: y
